name = "taxmate-api"
main = "src/index.ts"
compatibility_date = "2024-03-25"

[vars]
DATABASE_URL = ""
NEXTAUTH_SECRET = ""
NEXTAUTH_URL = "https://taxmate.pages.dev"
JWT_SECRET = ""

[[d1_databases]]
binding = "DB"
database_name = "taxmate-db"
database_id = "7b30c788-3a9a-43f0-8193-81a929bdc721"

[triggers]
crons = ["0 0 * * *"] # Run daily at midnight 